### ISSUE TITLE
login pb/ quick install

### ISSUE THREAD

**Issue by BioScrobe** [LeafLIMS/LeafLIMS#2]
Dear Leafs teams, 
I want to try the lims, and follow the quick start procedure from the installer.py
all seem good. 
Unfortunately, authentication fail with admin as user and password set installation process.
I check the password store in the settings.json file, its correct. 
but using this password and web application, it's failed.
do you have an issue.
Thanks

**Comment by tjomasc** [comment]
Thank you for your report, I've had a look into the issue and can't seem to replicate this myself. Can you check the following and let me know the outcome:

1. You have not run the installer before - the password is set when the system first starts at the end of the installer and afterwards can only be changed by logging in. Deleting the docker container and any associated volumes will reset this.
2. The password is the same in the .env file (this will likely be hidden) as the settings.json file.
3. Re-run the installer with --with-settings, wait at least 3 minutes to check it has successfully started and try logging in. If you try to log in too early it will not have fully started and will give a password error.

**Comment by Neuro-CS** [comment]
I have the same issue. I am running Leaf LIMS in Docker Toolbox on Windows 8. I was able to get around some issues (the .crt and .key file were not mounted and needed to be manually copied over via the Dockfile). I then arrived at the login screen. However, the password I set could not be used. I am locked out and all settings files (.env and settings.json) show the same password. I have deleted all containers/images/volumes and redone the install to no avail. When I run the installer with '--with-settings' it does not help. Any advice would be appreciated.

**Comment by tjomasc** [comment]
The various issues seem to be related to how Docker on Windows is handling the paths and values in the .env file. Based on what you have said I believe these are not being used and it is falling back to defaults. I'm afraid that until I have access to a system I can run both Windows and Docker I am going to be unable to fix these issues and I'd therefore recommend using Linux or a Mac as they have been fully tested.

**Comment by BioScrobe** [comment]
Hello,
Dear LeafTeams
Thank you so much for sharing LeafLIMS with the world!
 I will try to resume installation that I tried
my machine running on Ubuntu 16.04 up to date
I had erased all data concerning leaf file and docker
docker ps  → no container running
I had created a ssl key for this installation (self certifier) as described in the installation process
**version check**
**docker version** 
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

**docker compose version**
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 
2016
**Python version**
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Installation
**Download Zip LeafLims 3.0.zip** 
- extract here
- run installer ./installer.py and a second ./installer.py --with-settings


Docker run and start sucessfully
![image](https://user-images.githubusercontent.com/37416394/38384528-b2888d5a-390f-11e8-9692-23f5ba5971d4.png)

**Resume information**
DOMAIN=example.org
SETUP_ADMIN_EMAIL=mymail@outlook.fr
SETUP_ADMIN_PASSWORD=DD
FILE_STORE=/home/scrobe/Documents/sitesLeaf
CERT_LOCATION=/etc/ssl/server.crt
KEY_LOCATION=/etc/ssl/server.key
ORGANISATION_NAME=DDteams
PROJECT_IDENTIFIER_PREFIX=P
PROJECT_IDENTIFIER_START=100
EMAIL_HOST=localhost
EMAIL_PORT=465
EMAIL_HOST_PASSWORD=DD
EMAIL_HOST_USER=DD@localhost
EMAIL_USE_SSL=True
EMAIL_FROM=Leaf LIMS
ENABLE_CRM=False

DB_NAME=postgres
DB_PASSWORD=
DB_USER=postgres
DB_HOST=db
DB_PORT=5432g)

docker PS (information about containers) 
![image](https://user-images.githubusercontent.com/37416394/38384108-9a840af0-390e-11e8-8061-adcc9ad6b5f1.png)

Try to first connection 
admin and DD (password)

![image](https://user-images.githubusercontent.com/37416394/38384160-b1d42a6e-390e-11e8-9929-c6f452e36463.png)

I don't understand why the loggin don't work. If you have idea. Maybe I made a mistake somewhere,
any advice would be appreciated.
Thanks

**Comment by Neuro-CS** [comment]
That is too bad.

Is there a specific file in the docker image which stores the username/password for the website? A possible work around would to be copying a valid version of the file(s) over manually, in the same way I had to add the lines:

`COPY localhost.crt /etc/nginx/certs/ssl_cert.crt`
`COPY localhost.key /etc/nginx/certs/ssl_key.key`

into the frontend Dockerfile.

I am currently using most default settings with my domain set to "localhost:8000" and api_endpoint set to "https://localhost:8000/api/". Let me know if there is anything I can try to help troubleshoot.

**Comment by tjomasc** [comment]
@BioScrobe Looking at your configuration I can see the domain is set as example.org yet you are using localhost. Can you try setting this to localhost in your .env/settings.json file and let me know if this fixes your problem.

**Comment by tjomasc** [comment]
@Neuro-CS The password is set from the .env file data when first run, if the file cannot be read the password will be set as blank and you won't be able to log in. The alternative (which may work) is to set all of the environmental variables in the docker-compose.yml/Dockerfile file. This is a bit of a pain as you'll have to update everything manually when you upgrade and there's a lot of duplication but it should pick up the values. Copy the information from the .env file to the frontend/Dockerfile (starting each line with ENV) and then re-build.

**Comment by Neuro-CS** [comment]
@tjomasc I tried adding the environmental variables to the Dockerfile with "ENV " preceding them but it didn't work. I downloaded an Ubuntu VM to see if I could contrast a working and nonworking install, but found Ubuntu also failed to work at login. I'm wondering if the frontend is not correctly connecting to the backend. I can see in the console db_1 is receiving a connection from the backend at least. If you would like I can run the build command at the end of the install without "-d" and post the output.

**Comment by tjomasc** [comment]
@Neuro-CS That's odd, can you send me the output of running the Docker and I'll take a look. And just in case, can you make sure that the domain in your .env file matches the one you're running it on (e.g. if you're testing on localhost the domain should be set as localhost), if this is incorrect the frontend will not be able to see the backend to login.

**Comment by Neuro-CS** [comment]
@tjomasc I was able to get everything working on Ubuntu! It looks like the key issue was the timeout for the backend. Changing the command from:

`command: dockerize -wait tcp://db:5432 -timeout 30s bash -c "python manage.py migrate && python manage.py createinitialrevisions && python manage.py create_admin && daphne -b 0.0.0.0 -p 8000 lims.asgi:channel_layer"`

to

`command: dockerize -wait tcp://db:5432 -timeout 300s bash -c "python manage.py migrate && python manage.py createinitialrevisions && python manage.py create_admin && daphne -b 0.0.0.0 -p 8000 lims.asgi:channel_layer"`

resolved my current issues. For other people having any issues, my domain is simply "localhost" and other settings are set to default. I'll try running this same setup on Windows and comment how it works.

**Comment by Neuro-CS** [comment]
As for Windows: There is still a problem with mounting the file storage location which I haven't figured out. However, it can function with the following settings:

[Timeout set to 300s as above]
Domain: 192.168.99.100 (The IP specified by Docker on running the Quick Start Terminal)

**Comment by tjomasc** [comment]
@Neuro-CS That's great, in the version I'm currently testing the wait times have been changed to eliminate this problem, I've found a wait of 60s seems to be effective at solving the issue. I'll hopefully be releasing that next week once it's been running in our lab for long enough. 

I had a look at issues ongoing with Docker for Windows and it appears that this is an intermintent problem, I suggest trying the latest versions when they get released and seeing if that fixes things.

**Comment by BioScrobe** [comment]
@Neuro-CS 
Could you describe how did you installed and initialized the lims on linux,
I do not find where a made a mistake, I have always authentification problem. 
Thanks

**Comment by Neuro-CS** [comment]
@BioScrobe During installation, what happens when you set your domain to "localhost"? Also, edit docker-compose.yml and change the following line:

`command: dockerize -wait tcp://db:5432 -timeout 30s bash -c "python manage.py migrate && python manage.py createinitialrevisions && python manage.py create_admin && daphne -b 0.0.0.0 -p 8000 lims.asgi:channel_layer"`

to

`command: dockerize -wait tcp://db:5432 -timeout 300s bash -c "python manage.py migrate && python manage.py createinitialrevisions && python manage.py create_admin && daphne -b 0.0.0.0 -p 8000 lims.asgi:channel_layer"`

Does this solve your problem?

**Comment by tjomasc** [comment]
I've just release version 3.1 if you are still having problems could you give that a try and let me know the outcome?

**Comment by BioScrobe** [comment]
Hello, 
I will try and I came back to you !
thank

**Comment by BioScrobe** [comment]
Hello, 
I' tried new version with the same procedure (first message) and it gave the same results. I was not able to authentication, however
I think I found a solution, but I don't understand "how it works" 

I stop and remove all docker with command line
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

and use command line describe in part "I don't think it worked! "
 docker-compose -p localhost up --build 
(where I have just replace leaflims by localhost) 

and now it works very fine and I can explore your LIMS

Thanks for your help.

**Comment by tjomasc** [comment]
@BioScrobe That sounds to me like it was still using the old data, Leaf LIMS stores all it's data in a volume that gets reused. By deleting and recreating the volume you've made sure that it uses the latest password in the configuration and creates a new volume to use.
