### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by synth-bio** [LeafLIMS/LeafLIMS#3]
Dear LeafLIMS team

Nice paper.  I failed to install the software after spending 3h (including the writing of this). I followed the instructions but I'm afraid it doesn't work as said (at least for somebody who is not a software developer, although I have many years experience with Unix adm and in software engineering). I've tried to install it first on my laptop to test it. I don't have there an apache server (but it is not required according to your "Prerequisites" section). I created a self-signed SSL certificate by doing this:
openssl req -x509 -newkey rsa:4096 -keyout alfonso.key -out alfonso.crt -days 365

Then, when asked by the path to the .crt/.key files by the installer I just provide the directory where I run the previous command. I installed docker for Mac (which already includes Docker Compose). After setting the password, still you need to setup the database server password (no idea of how to do it quickly, after trying a few things). So I left it blank, which still should be Ok (?). I understand that you rely on a third party software (Docker) but it would be essential if you could explicitly indicate a minimal installation to work with LeafLIMS. I (and probably most people in synthetic biology) don't plan to use Docker for anything else (and I will remove it from my computer if finally I don't use your software).

I try to point a web server but it didn't work. I scanned my local ports for all servers and I didn't see any web server, so it is not an SSL issue. 

Thanks in advance for your help

Best regards

Alfonso

**Comment by tjomasc** [comment]
Please see https://github.com/LeafLIMS/LeafLIMS/releases/tag/3.1 for a potential fix to this issue.
