### ISSUE TITLE
Barcode generator / printer

### ISSUE THREAD

**Issue by gringer** [LeafLIMS/LeafLIMS#4]
Our research institute is currently hunting around for an inventory management system, and I noticed that LeafLIMS does inventory tracking. One thing I noticed from the documentation is that it had a "barcode" field for inventory, but didn't seem to have an ability to generate and print out barcodes.

Could this be added?

I'm aware that Inkscape has its own barcode generator and is scriptable, so maybe just a wrapper around an external command would be good enough.

**Comment by tjomasc** [comment]
Thanks for the suggestion! After thinking about the logistics of creating barcodes I've come to the conclusion that it's best left to a dedicated program. Whilst it is simple to create barcodes it is not as easy to have these work correctly with the various barcode printers and potential label sizes that exist.

Though more long winded you can export a CSV file from the inventory and use that as the source of information for dedicated barcode creation and printing program.
