### ISSUE TITLE
Is local deployment possible ?

### ISSUE THREAD

**Issue by Zulko** [LeafLIMS/LeafLIMS#5]
Hey there,

I am trying to test LeafLIMS locally but I am not sure if it is possible to get certificates for "localhost", and it seems that LeafLIMS won't launch without certificates. Is there an easy way to deploy locally ?

Cheers,

**Comment by tjomasc** [comment]
Yep, it's possible but you'll have to generate your own self-signed SSL certificates. This isn't difficult (This page on lets encrypt which talks about different ways to do it: https://letsencrypt.org/docs/certificates-for-localhost/) and you can then just use those certificates locally. Your browser will warn you about trusting them but you can just accept that and it will work.

**Comment by Zulko** [comment]
Thank, it worked ! Somehow I had stopped at the beginning of the page, but the command at the end did the trick:

```
openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

This produces ``./localhost.key`` and ``./localhost.cert`` which you then feed to the installer, and the front end works.
