### ISSUE TITLE
Not able to log in LeafLIMS on a VM instance or localhost

### ISSUE THREAD

**Issue by sqilz** [LeafLIMS/LeafLIMS#7]
I have tried many things, most of my issues are similar to those from the previous and now Closed Issue tickets,
I have generated a localhost certs from https://letsencrypt.org/docs/certificates-for-localhost/
The website (runs on docker, and is accessible via browser) but not able to login with admin account and new accounts I created with `python manage.py createsuperuser`  i managed to install and run LeafLIMS only once, the admin account didn't work and that command worked and created a new user I managed to log in with. 
But I could not reproduce that again in new setups, both locally and on my VM (ubuntu)

I have tried `docker-compose -p leaflims2 up --build` and reinstalling with `--with-settings`

Also I wanted to add that when  runnign `python manage.py createsuperuser`  it does create a user, which shows in `auth_users` table in the database however I am also not able to log in with that new user

Tried in my own cloud and also in the http://cloud.google.com - same issue, double checked the ports, and they allow for both HTTP and HTTPS traffic

**Comment by tjomasc** [comment]
I think this might be an issue with initial user creation. When you very first start the Docker instance it creates the user account from the password in the .env file (which is set either manually or by the installer). If this is missing you won't be able to log in. Leaf LIMS also doesn't use the superuser flag so running createsuperuser won't give you the permissions to log in.

Unfortuntly the only way to fix this is to delete the docker volume that contains the data and start again. You can do this by first deleting the container (docker rm leaflims_db) and then the volume (docker volume rm leaflims_lims_data). Once this is done ensure that the password in the .env file is correct and start everything up. The database is then recreated with the password you specified.

If you're still having problems I can suggest trying a different password (in case there's something causing it not to be picked up) and if you still have problems let me know.

**Comment by sqilz** [comment]
@tjomasc renaming the env.template to .env and setting it up manually has solved the issue
